spring:
  application:
    name: test
# 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: test
    url: jdbc:mysql://10.1.1.151:3306/taxdev?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
# mapper文件配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl